---
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes


- name: remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes

- name: "install dependencies."
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: Creates directory
  file:
    path: /home/ubuntu/backend/
    state: directory

- name: Copy index test page
  copy:
    src: "~/project/artifact.tar.gz"
    dest: "/home/ubuntu/backend/"

- name: Untar
  shell: |
    tar -xf /home/ubuntu/backend/artifact.tar.gz /home/ubuntu/backend

- name: Executing node
  shell: |
    pm2 stop default
    pm2 start npm -- start
